//
//  CountryDetailPresenter.swift
//  S.Kh_Task_21
//
//  Created by Saba Khitaridze on 11.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountryDetailPresenterProtocol {
    func presentCountryDetails(response: CountryDetail.InfoData)
}

class CountryDetailPresenter {
    weak var viewController: CountryDetailDisplayLogic?
    
}

extension CountryDetailPresenter: CountryDetailPresenterProtocol {
    
    func presentCountryDetails(response: CountryDetail.InfoData) {
        let country = response.country
        
        //currencies
        var currencyArray = [DetailCurrencyViewModel]()
        country.currencies.forEach({
            currencyArray.append(DetailCurrencyViewModel(code: $0.code,
                                                         name: $0.name,
                                                         symbol: $0.symbol))
        })
        
        let viewModel = CountryDetailModel(name: country.name,
                                           alphaCode: country.alphaCode,
                                           capital: country.capital,
                                           region: country.region,
                                           pupulation: country.pupulation,
                                           flag: country.flag,
                                           currencies: currencyArray)
        
        viewController?.displayCountryDetail(viewModel: viewModel)
    }
    
}
