//
//  CountryInteractor.swift
//  S.Kh_Task_21
//
//  Created by Saba Khitaridze on 11.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountryInteractorProtocol: AnyObject {
   func getCountries()
}

class CountryInteractor {
  var presenter: CountryPresenterProtocol?
  private var worker: CountryWorker?
    
}


extension CountryInteractor: CountryInteractorProtocol {
    
    func getCountries() {
      worker = CountryWorker()
        worker?.getCountries(result: { countries in
            let response = CountryModel.Response(countries: countries)
            self.presenter?.presentCountries(response: response)
        })
    }
    
}
