//
//  CountryWorker.swift
//  S.Kh_Task_21
//
//  Created by Saba Khitaridze on 11.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountryWorkerProtocol {
    func getCountries(result: @escaping ([Country]) -> ())
}

class CountryWorker: CountryWorkerProtocol {
    
    func getCountries(result: @escaping ([Country]) -> ()) {
        Fetcher.fetchData(with: CountryUrlBuilder.shared.urlString, as: [Country].self) { countries in
            result(countries)
        }
    }
    
}
