//
//  CountryModels.swift
//  S.Kh_Task_21
//
//  Created by Saba Khitaridze on 11.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias CountryViewModel = CountryModel.ViewModel.DisplayedCountry
typealias CurrencyViewModel = CountryModel.ViewModel.Currency

enum CountryModel {
    
    struct Request {}
    
    struct Response {
        let countries: [Country]
    }
    
    struct ViewModel {
        
        struct DisplayedCountry {
            let name: String
            let alphaCode: String
            let capital: String
            let region: String
            let pupulation: Int
            let flag: String
            let currencies: [Currency]
        }
        
        var displayedCountries: [DisplayedCountry]
        
        struct Currency {
            let code, name, symbol: String
        }
    }

}
